services:
  api-service:
    build: ./Node-API
    container_name: api-1
    ports:
     - 4000:4000
    volumes:
      - /Users/gic-lpt-0183/Batch-1/Docker-Training/Book-App/Node-API:/app
  
  frontend-service:
      build: ./Frontend
      container_name: book-app-container
      ports:
        - 3000:80
      depends_on:
       - api-service